package com.sample.air.quote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-25T14:45:52.961+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "AirLineQuoteService", 
                  wsdlLocation = "file:/D:/javaEx3/ReservationService/src/main/resources/wsdl/ReservationService.wsdl",
                  targetNamespace = "http://air.sample.com/quote/") 
public class AirLineQuoteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://air.sample.com/quote/", "AirLineQuoteService");
    public final static QName AirLineQuoteSOAP = new QName("http://air.sample.com/quote/", "AirLineQuoteSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/javaEx3/ReservationService/src/main/resources/wsdl/ReservationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AirLineQuoteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/javaEx3/ReservationService/src/main/resources/wsdl/ReservationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AirLineQuoteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AirLineQuoteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirLineQuoteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirLineQuote
     */
    @WebEndpoint(name = "AirLineQuoteSOAP")
    public AirLineQuote getAirLineQuoteSOAP() {
        return super.getPort(AirLineQuoteSOAP, AirLineQuote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirLineQuote
     */
    @WebEndpoint(name = "AirLineQuoteSOAP")
    public AirLineQuote getAirLineQuoteSOAP(WebServiceFeature... features) {
        return super.getPort(AirLineQuoteSOAP, AirLineQuote.class, features);
    }

}
