FROM openjdk:8-jre-alpine
ADD target/quick-start-dockerfile-0.0.1-SNAPSHOT.jar quick-start-dockerfile-0.0.1-SNAPSHOT.jar
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "quick-start-dockerfile-0.0.1-SNAPSHOT.jar"]