package com.sample.airb.quote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-09-25T14:45:53.414+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://airb.sample.com/quote/", name = "AirLineBQuote")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AirLineBQuote {

    @WebResult(name = "getQuoteResponse", targetNamespace = "http://airb.sample.com/quote/", partName = "parameters")
    @WebMethod(action = "http://airb.sample.com/quote/getQuoteOperation")
    public GetQuoteResponse getQuoteOperation(
        @WebParam(partName = "parameters", name = "getQuote", targetNamespace = "http://airb.sample.com/quote/")
        GetQuote parameters
    ) throws GetQuoteOperationFault;
}
